package com.nikita.creditrisk.model;

import java.util.List;

/**
 * Response DTO containing the full AI-generated credit risk explanation.
 * 
 * SPRING AI - RESPONSE FORMATTING:
 * This structured response is generated by parsing AI output using
 * BeanOutputConverter / JSON structured output from the LLM.
 */
public class RiskExplanationResponse {

    private String customerId;
    private int creditScore;
    private String riskLevel;              // HIGH, MEDIUM, LOW
    private String scoreInterpretation;
    private List<RiskFactorDetail> keyFactors;
    private List<PolicyViolation> policyViolations;
    private List<String> recommendations;
    private String complianceStatus;       // COMPLIANT, PARTIALLY_COMPLIANT, NON_COMPLIANT
    private String summary;
    private String processingMode;         // AI or FALLBACK
    private String timestamp;

    // --- Inner class for risk factor details ---
    public static class RiskFactorDetail {
        private String factor;
        private String impact;
        private String description;

        public RiskFactorDetail() {}
        public RiskFactorDetail(String factor, String impact, String description) {
            this.factor = factor;
            this.impact = impact;
            this.description = description;
        }

        public String getFactor() { return factor; }
        public void setFactor(String factor) { this.factor = factor; }
        public String getImpact() { return impact; }
        public void setImpact(String impact) { this.impact = impact; }
        public String getDescription() { return description; }
        public void setDescription(String description) { this.description = description; }
    }

    // --- Inner class for policy violations ---
    public static class PolicyViolation {
        private String policyName;
        private String section;
        private String violation;
        private String severity;

        public PolicyViolation() {}
        public PolicyViolation(String policyName, String section, String violation, String severity) {
            this.policyName = policyName;
            this.section = section;
            this.violation = violation;
            this.severity = severity;
        }

        public String getPolicyName() { return policyName; }
        public void setPolicyName(String policyName) { this.policyName = policyName; }
        public String getSection() { return section; }
        public void setSection(String section) { this.section = section; }
        public String getViolation() { return violation; }
        public void setViolation(String violation) { this.violation = violation; }
        public String getSeverity() { return severity; }
        public void setSeverity(String severity) { this.severity = severity; }
    }

    // --- Main class Getters and Setters ---
    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }
    public int getCreditScore() { return creditScore; }
    public void setCreditScore(int creditScore) { this.creditScore = creditScore; }
    public String getRiskLevel() { return riskLevel; }
    public void setRiskLevel(String riskLevel) { this.riskLevel = riskLevel; }
    public String getScoreInterpretation() { return scoreInterpretation; }
    public void setScoreInterpretation(String scoreInterpretation) { this.scoreInterpretation = scoreInterpretation; }
    public List<RiskFactorDetail> getKeyFactors() { return keyFactors; }
    public void setKeyFactors(List<RiskFactorDetail> keyFactors) { this.keyFactors = keyFactors; }
    public List<PolicyViolation> getPolicyViolations() { return policyViolations; }
    public void setPolicyViolations(List<PolicyViolation> policyViolations) { this.policyViolations = policyViolations; }
    public List<String> getRecommendations() { return recommendations; }
    public void setRecommendations(List<String> recommendations) { this.recommendations = recommendations; }
    public String getComplianceStatus() { return complianceStatus; }
    public void setComplianceStatus(String complianceStatus) { this.complianceStatus = complianceStatus; }
    public String getSummary() { return summary; }
    public void setSummary(String summary) { this.summary = summary; }
    public String getProcessingMode() { return processingMode; }
    public void setProcessingMode(String processingMode) { this.processingMode = processingMode; }
    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }
}
